# Generated by Django 4.0.6 on 2022-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Noticia', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
