# Generated by Django 4.0.6 on 2022-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_title_alter_news_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Anonimo', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.CharField(default='Noticia', max_length=500),
        ),
    ]
