# Generated by Django 4.0.6 on 2022-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news_author_news_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
